#!/usr/bin/env bash

if
  [[ -s "/Users/ccoupe/.rvm/gems/ruby-2.1.6@global/environment" ]]
then
  source "/Users/ccoupe/.rvm/gems/ruby-2.1.6@global/environment"
  exec executable-hooks-uninstaller "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/ccoupe/.rvm/gems/ruby-2.1.6@global/environment'" >&2
  exit 1
fi
